### ISSUE TITLE
Example request to trias service

### ISSUE THREAD

**Issue by hypervtechnics** [VDVde/TRIAS#1]
Would you provide an example request to a trias service? E.g. Location Information Request with Initial input because the general structure is not clear.

Things mentioned should be:
- URL
- Method
- Body
- Headers

I tried with the following body and get a 400 : 

```
<?xml version="1.0" encoding="utf-8"?>
<Trias
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" version="1.2"
	xmlns="http://www.vdv.de/trias">
	<ServiceRequest>
		<ServiceRequestContext
			xmlns="http://www.siri.org.uk/siri">
			<DataNameSpaces />
			<MultipartDespatch>false</MultipartDespatch>
		</ServiceRequestContext>
		<RequestPayload>
			<LocationInformationRequest>
				<InitialInput>
					<LocationName>Düsseldorf</LocationName>
				</InitialInput>
				<Restrictions>
					<Type>stop</Type>
				</Restrictions>
			</LocationInformationRequest>
		</RequestPayload>
	</ServiceRequest>
</Trias>
```

as POST request to the trias endpoint.

**Comment by forgemo** [comment]
A very simple working example is:

```xml
<Trias version="1.2" xmlns="http://www.vdv.de/trias" xmlns:siri="http://www.siri.org.uk/siri">
    <ServiceRequest>
        <siri:RequestTimestamp>2019-02-17T12:14:01.139+01:00</siri:RequestTimestamp>
        <RequestPayload>
            <LocationInformationRequest>
                <InitialInput>
                    <LocationName>Düsseldorf</LocationName>
                </InitialInput>
            </LocationInformationRequest>
        </RequestPayload>
    </ServiceRequest>
</Trias>
```

URL: The endpoint, you have access to
METHOD: Post
Body: My example from above
Headers: Content-Type: text/xml

Please make sure, that the trias version matches the version of your endpoint. In this examples case, it is `1.2`

**Comment by hypervtechnics** [comment]
@forgemo Thank you for your answer. I tried your solution and it gave me the error 400 again. I started to play with the URL and came to the conclusion that the url published by the company was wrong. Some kind of an error I did not thought of...

PS: Both your and my body worked perfectly after trying with the correct URL :)

**Comment by nomaanhusain** [comment]
What is the correct URL? Did you find it?
